### ISSUE TITLE
Time to fail safe value is displayed 10 times greater than in the saved config file

### ISSUE THREAD

**Issue by macrokernel** [mosvov/qczek-modules-setting#1]
The configuration tool is displaying Time to fail safe value as "200", while in the saved config it is "{ParSetInt timeToFS 20}".

Another one is that the parameter description in the config tool is saying that the units of this value is seconds, while according to Krzysztof http://qczek.beyondrc.com/qczek-lrs-433mhz-1w-lora-rc-link/qczek-lrs-configuration/ it is tenths of seconds. Same for the Reset RX if no signal input field.

**Comment by mosvov** [comment]
Thanks for reporting,
there was error in timeToFS calculation, will be fixed.

In UI you will see timeToFS and Reset RX (wdTime) in seconds.  In config timeToFS will be passed as tenths of seconds value, and wdTime in seconds.

**Comment by macrokernel** [comment]
Thanks for fixing.
